# urls.py

from django.urls import path
from .views import *
from rest_framework_simplejwt.views import TokenRefreshView

urlpatterns = [
    path('registration/', UserRegistrationView.as_view(), name='user-registration'),
    path('login/', UserLoginView.as_view(), name='user-login'),
    path('logout/', UserLogoutView.as_view(), name='user-logout'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token-refresh'),
    path('create-project/', CreateProjectView.as_view(), name='create-project'),
    path('get-all-projects-list/', GetAllProjectsListView.as_view(), name='get-all-projects-list'),
    path('get-my-projects-list/', GetMyProjectsListView.as_view(), name='get-my-projects-list'),
    path('project/<int:pk>/get-details/', GetProjectDetailsView.as_view(), name='get-project-details'),
    path('project/<int:pk>/change-status/', ChangeProjectStatusView.as_view(), name='change-project-status'),
    path('project/<int:pk>/delete/', DeleteProjectView.as_view(), name='delete-project'),
    path('project/<int:pk>/change-info/', ChangeProjectView.as_view(), name='change-project-info'),
    path('project/<int:pk>/create-request/', CreateProjectRequestView.as_view(), name='create-project-request'),
    path('project/<int:pk>/get-none-users/', GetUsersNotInProjectView.as_view(), name='project-none-users'),
    path('project/<int:pk>/get-users/', GetUsersInProjectView.as_view(), name='project-users'),
    path('project/<int:pk>/get-requests/', GetProjectRequestsView.as_view(), name='project-get-requests'),
    path('project/<int:pk>/add-member/', AddProjectMemberView.as_view(), name='project-add-member'),
    path('project/<project_id>/request/<int:pk>/set-status/', SetProjectRequestStatusView.as_view(), name='project-set-request-status'),
    path('project/<project_id>/remove-member/<user_id>/', RemoveProjectMemberView.as_view(), name='project-remove-member'),
    path('project/<project_id>/get-all-tasks/', GetAllTasksView.as_view(), name='project-get-all-tasks'),
    path('project/<project_id>/get-my-tasks/', GetMyTasksView.as_view(), name='project-my-tasks'),
    path('project/<project_id>/get-my-tasks-to-others/', GetMyTasksToOthersView.as_view(), name='project-get-my-tasks-to-others'),
    path('project/<project_id>/get-not-private-tasks/', GetNotPrivateTasksView.as_view(), name='project-get-not-private-tasks'),
    path('project/<project_id>/get-user-group/', GetUserProjectGroupView.as_view(), name='get-user-project-group'),
    path('create-task/', CreateTaskView.as_view(), name='create-task'),
    path('task/<int:pk>/get-details/', GetTaskDetailsView.as_view(), name='get-task-details'),
    path('task/<int:pk>/change-status/', ChangeTaskStatusView.as_view(), name='change-task-status'),
    path('task/<int:pk>/delete/', DeleteTaskView.as_view(), name='delete-task'),
    path('task/<int:pk>/change-info/', ChangeTaskView.as_view(), name='change-task-info'),
    path('task/<int:pk>/get-comments/', GetCommentsByTaskIdView.as_view(), name='task-get-comments'),
    path('create-comment/', CreateCommentView.as_view(), name='create-comment'),
    path('comment/<int:pk>/delete/', DeleteCommentView.as_view(), name='delete-comment'),
    path('comment/<int:pk>/edit/', ChangeCommentView.as_view(), name='edit-comment'),
    path('get-user-profile-info/', GetUserProfileInfo.as_view(), name='get-user-profile-info'),
    path('change-user-profile-info/', ChangeUserProfileInfoView.as_view(), name='change-user-profile-info'),
    path('delete-user-account/', DeleteUserAccount.as_view(), name='delete-user-account'),
    path('project/<project_id>/change-member-group/', ChangeMemberGroupView.as_view(), name='project-change-member-group'),
    path('get-all-users-info/', GetAllUsersInfoView.as_view(), name='get-all-users-info'),
    path('change-project-leader-rights/', ChangeProjectLeaderRightsView.as_view(), name='change-project-leader-rights'),
    path('change-account-activation/', ChangeActivationView.as_view(), name='change-account-activation'),
    path('project/<project_id>/statistics/status-distribution/', TaskStatusDistributionView.as_view(), name='project-statistics-status-distribution'),
    path('project/<project_id>/statistics/priority-distribution/', TaskPriorityDistributionView.as_view(), name='project-statistics-priority-distribution'),
    path('project/<project_id>/statistics/overloaded-users/', OverloadedUsersView.as_view(), name='project-statistics-overloaded-users'),
    path('project/<project_id>/statistics/underloaded-users/', UnderloadedUsersView.as_view(), name='project-statistics-underloaded-users'),
    path('project/<project_id>/statistics/task-status-distribution/user/<user_id>/', TaskDistributionByUserView.as_view(), name='project-statistics-user-task-distribution'),
    path('get-action-types/', GetActionTypesView.as_view(), name='get-action-types'),
    path('get-actions/user/<user_id>/type/<type_id>/', GetUsersActionsView.as_view(), name='get-user-actions'),
    path('password-reset/', PasswordResetView.as_view(), name='password-reset'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
]