# Generated by Django 5.1.1 on 2025-03-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='due_date',
            field=models.DateField(),
        ),
    ]
