# Generated by Django 5.1.1 on 2025-05-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0004_alter_tasks_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_projects',
            name='date_joined_project',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
