# Generated by Django 5.1.1 on 2025-05-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0005_users_projects_date_joined_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_projects',
            name='date_joined_project',
            field=models.DateField(auto_now_add=True),
        ),
    ]
